# Generated by Django 3.1.6 on 2021-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='책 이름', help_text='책 이름을 입력하세요', max_length=100)),
                ('price', models.IntegerField(default=0, help_text='책 가격')),
                ('category', models.CharField(choices=[('Freshmen', '1학년'), ('Computer', '컴퓨터공학과'), ('Electronics', '전기공학과'), ('Elective', '교양'), ('ETC', '기타')], default='ETC', help_text='책의 종류를 선택하세요', max_length=100)),
            ],
        ),
    ]
