# Generated by Django 3.1.6 on 2021-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='', help_text='책 이름을 입력하세요', max_length=100),
        ),
    ]
