# Generated by Django 3.1.6 on 2021-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='people',
            field=models.ManyToManyField(blank=True, help_text='해당 책을 선택한 사람들의 목록입니다.', to='auction.Person'),
        ),
    ]
