# Generated by Django 3.1.6 on 2021-02-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='가구 이름을 입력하세요', max_length=100)),
                ('price', models.IntegerField(default=0, help_text='가구 가격')),
                ('image', models.ImageField(blank=True, help_text='가구의 이미지를 업로드하세요', null=True, upload_to='images/furniture')),
                ('people', models.ManyToManyField(blank=True, help_text='해당 가구를 선택한 사람들의 목록입니다.', to='auction.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ETC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='이름을 입력하세요', max_length=100)),
                ('price', models.IntegerField(default=0, help_text='가격')),
                ('image', models.ImageField(blank=True, help_text='이미지를 업로드하세요', null=True, upload_to='images/etc')),
                ('people', models.ManyToManyField(blank=True, help_text='해당 물품을 선택한 사람들의 목록입니다.', to='auction.Person')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='보드게임 이름을 입력하세요', max_length=100)),
                ('price', models.IntegerField(default=0, help_text='보드게임 가격')),
                ('image', models.ImageField(blank=True, help_text='보드게임의 이미지를 업로드하세요', null=True, upload_to='images/boardGames')),
                ('people', models.ManyToManyField(blank=True, help_text='해당 보드게임을 선택한 사람들의 목록입니다.', to='auction.Person')),
            ],
        ),
    ]
