# Generated by Django 3.1.6 on 2021-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20210212_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='quantity',
            field=models.IntegerField(default=1, help_text='수량'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1, help_text='수량'),
        ),
        migrations.AddField(
            model_name='etc',
            name='quantity',
            field=models.IntegerField(default=1, help_text='수량'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='quantity',
            field=models.IntegerField(default=1, help_text='수량'),
        ),
    ]
