# Generated by Django 3.1.6 on 2021-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auto_20210213_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Freshmen', '1학년'), ('Computer', '컴공'), ('Electrical', '전기'), ('Electric', '전자'), ('Elective', '교양'), ('ETC', '기타')], default='ETC', help_text='책의 종류를 선택하세요', max_length=100),
        ),
    ]
