# Generated by Django 3.1.6 on 2021-02-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='origin_price',
            field=models.IntegerField(default=0, help_text='원래 금액 / 모르면 0원'),
        ),
        migrations.AlterField(
            model_name='book',
            name='origin_price',
            field=models.IntegerField(default=0, help_text='원래 금액 / 모르면 0원'),
        ),
        migrations.AlterField(
            model_name='etc',
            name='origin_price',
            field=models.IntegerField(default=0, help_text='원래 금액 / 모르면 0원'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='origin_price',
            field=models.IntegerField(default=0, help_text='원래 금액 / 모르면 0원'),
        ),
    ]
